version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: teams_proto
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - '3306:3306'
